export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCTS_ERROR = 'DESCARGA_PRODUCTOS_ERROR'

export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS'
export const GET_PRODUCT_DETAILS_ERROR = 'GET_PRODUCT_DETAILS_ERROR'

export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR'

export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const EDIT_PRODUCT_ERROR = 'EDIT_PRODUCT_ERROR'
export const HOUSE_TO_UPDATE = 'HOUSE_TO_UPDATE'

export const NEW_PRODUCT = 'NEW_PRODUCT'
export const NEW_PRODUCT_ERROR = 'NEW_PRODUCT'

